/**
 * OWASP Top 10:2025 - static reference data.
 *
 * Mirrors the published 2025 list (https://owasp.org/Top10/2025/) in release
 * order. The notable changes from the 2021 edition are captured here: A03 is
 * now Software Supply Chain Failures (absorbing Vulnerable and Outdated
 * Components), Injection is a single A05, SSRF is folded into A01, and A10 is
 * Mishandling of Exceptional Conditions instead of SSRF. `wstgFocus` points at
 * the OWASP WSTG v4.2 test ids that primarily exercise each category.
 */

import type { OwaspTop10Category } from "./types";

export const OWASP_TOP10_2025_VERSION = "2025";
export const OWASP_TOP10_2025_SOURCE = "https://owasp.org/Top10/2025/";

export const OWASP_TOP10_2025: OwaspTop10Category[] = [
  {
    id: "A01:2025",
    rank: 1,
    title: "Broken Access Control",
    summary:
      "Requests that reach data or functionality the caller is not authorised for: missing function-level checks, IDOR, forced browsing, path traversal, over-permissive CORS and SSRF, which was folded into this category for 2025 instead of keeping its own rank. CSRF remains part of Broken Access Control.",
    cwes: [
      "CWE-22",
      "CWE-284",
      "CWE-285",
      "CWE-352",
      "CWE-425",
      "CWE-639",
      "CWE-862",
      "CWE-863",
      "CWE-918",
    ],
    wstgFocus: [
      "WSTG-ATHZ-02",
      "WSTG-ATHZ-03",
      "WSTG-ATHZ-04",
      "WSTG-ATHZ-01",
      "WSTG-INPV-19",
      "WSTG-SESS-05",
      "WSTG-CLNT-07",
      "WSTG-CONF-05",
    ],
    detection: [
      "Endpoints that return another user's object when an id, filename or token is swapped.",
      "Low-privilege sessions receiving success responses from privileged pages or API routes.",
      "Traversal payloads in file, path or template parameters returning content from outside the intended directory.",
      "Server-side requests reaching loopback, RFC1918 or cloud metadata addresses from URL parameters.",
      "CORS responses echoing an attacker origin while allowing credentials.",
    ],
    remediation: [
      "Enforce one server-side authorisation check per request that denies by default and cannot be bypassed by path, verb or header changes.",
      "Resolve objects through server-side ownership lookups (session-scoped queries) instead of trusting client-supplied identifiers.",
      "Centralise CORS allow-lists, never reflect arbitrary origins, and never combine wildcard origins with credentials.",
      "Allow-list outbound destinations for server-side fetches and block link-local, loopback and metadata addresses.",
      "Require anti-CSRF tokens or SameSite cookies on state-changing requests and re-check authorisation server-side.",
    ],
  },
  {
    id: "A02:2025",
    rank: 2,
    title: "Security Misconfiguration",
    summary:
      "Missing, incomplete or default hardening anywhere in the stack: default accounts and sample files, verbose errors, unnecessary features and ports, permissive HTTP methods, weak browser security headers, and insecure cloud or container defaults. Parser-level XML abuse now sits under Injection, so 2025 concentrates this category on configuration itself.",
    cwes: [
      "CWE-16",
      "CWE-200",
      "CWE-260",
      "CWE-315",
      "CWE-520",
      "CWE-547",
      "CWE-614",
      "CWE-756",
      "CWE-942",
      "CWE-1004",
      "CWE-1174",
    ],
    wstgFocus: [
      "WSTG-CONF-02",
      "WSTG-CONF-03",
      "WSTG-CONF-04",
      "WSTG-CONF-06",
      "WSTG-CONF-07",
      "WSTG-CONF-08",
      "WSTG-INPV-16",
      "WSTG-CLNT-09",
    ],
    detection: [
      "Default pages, sample applications, directory listings or management consoles answering on the tested host.",
      "Banners, stack traces or debug output naming versions, frameworks and internal paths.",
      "Unexpected verbs accepted, method overrides honoured, TRACE enabled or directory listing on.",
      "Missing or weak Strict-Transport-Security, Content-Security-Policy, X-Frame-Options and X-Content-Type-Options headers.",
      "Cross-domain policy files, storage buckets or network ports exposed beyond what the application needs.",
    ],
    remediation: [
      "Build every environment from a hardened baseline and manage configuration as code with automated drift detection.",
      "Remove default accounts, sample files, unused modules, debug consoles and management interfaces from production.",
      "Reject unexpected HTTP methods and normalise paths at the edge instead of rewriting malformed requests.",
      "Ship security headers from one shared middleware (HSTS with preload, CSP, frame-ancestors, nosniff) so no route is missed.",
      "Return generic error responses to clients while logging detail server-side, and treat configuration change as a reviewed release step.",
    ],
  },
  {
    id: "A03:2025",
    rank: 3,
    title: "Software Supply Chain Failures",
    summary:
      "New at third position in 2025, absorbing Vulnerable and Outdated Components: compromised, unmaintained or unverified dependencies, build and CI/CD pipelines, third-party scripts and hosted services, and the provenance of everything the application ships. Most findings that would once have been an outdated component now land here.",
    cwes: [
      "CWE-345",
      "CWE-494",
      "CWE-829",
      "CWE-937",
      "CWE-1104",
      "CWE-1329",
      "CWE-1357",
      "CWE-1395",
    ],
    wstgFocus: [
      "WSTG-INFO-09",
      "WSTG-INFO-02",
      "WSTG-INFO-08",
      "WSTG-CONF-10",
      "WSTG-CONF-11",
      "WSTG-CLNT-06",
      "WSTG-CLNT-13",
    ],
    detection: [
      "Component, plug-in or library versions that map to known CVEs or are end-of-life.",
      "Third-party scripts and assets loaded without Subresource Integrity or a pinned version.",
      "Dangling DNS records pointing at unclaimed cloud or SaaS resources.",
      "Publicly listable or writable storage buckets serving application assets.",
      "Build inputs or deployment artefacts fetched from untrusted, unsigned sources.",
    ],
    remediation: [
      "Inventory every dependency including transitive and container layers, and continuously match it against vulnerability feeds.",
      "Pin exact versions with committed lockfiles and review upgrades through automated dependency pull requests.",
      "Verify integrity of everything executed: SRI for browser assets, signatures or checksums for build and deployment inputs.",
      "Delete orphaned DNS records and decommission third-party services as part of the release process.",
      "Secure the pipeline with signed commits and artefacts, least-privilege build credentials and reproducible builds.",
    ],
  },  {
    id: "A04:2025",
    rank: 4,
    title: "Cryptographic Failures",
    summary:
      "Confidentiality lost through missing, weak or misapplied cryptography: plain-text transmission, obsolete protocols and ciphers, hard-coded or reused keys, weak password hashing and unauthenticated encryption. Padding-oracle and weak-TLS findings remain here in the 2025 list.",
    cwes: [
      "CWE-261",
      "CWE-310",
      "CWE-319",
      "CWE-321",
      "CWE-326",
      "CWE-327",
      "CWE-328",
      "CWE-522",
      "CWE-759",
      "CWE-916",
    ],
    wstgFocus: [
      "WSTG-CRYP-01",
      "WSTG-CRYP-02",
      "WSTG-CRYP-03",
      "WSTG-CRYP-04",
      "WSTG-ATHN-01",
      "WSTG-ATHN-05",
    ],
    detection: [
      "SSLv2/v3 or TLS 1.0/1.1 accepted, or RC4, 3DES, NULL and export ciphers offered.",
      "Credentials, tokens or personal data sent over http:// or non-TLS protocols, or protected by encoding alone.",
      "Distinct error messages, status codes or timing for invalid padding or MAC on encrypted values.",
      "MD5, SHA-1, unsalted or fast hashes protecting passwords, and hard-coded or shared keys.",
      "Certificates that are expired, misnamed, untrusted or missing intermediates.",
    ],
    remediation: [
      "Require TLS 1.2+ with modern cipher suites, HSTS, complete certificate chains and automated renewal.",
      "Protect sensitive data in transit and at rest with vetted libraries, authenticated modes such as AES-GCM, and per-purpose keys from a key management service.",
      "Hash passwords with bcrypt, scrypt or Argon2, choosing work factors from measured cost rather than a constant.",
      "Remove hard-coded keys and secrets from source control, load them from a secret manager and rotate on exposure.",
      "Fail closed with uniform error responses so decryption or padding behaviour cannot be used as an oracle.",
    ],
  },
  {
    id: "A05:2025",
    rank: 5,
    title: "Injection",
    summary:
      "One category for every interpreter-injection flaw in 2025: SQL, NoSQL, ORM and OS command injection, LDAP and XPath injection, template and expression injection, HTTP header injection and cross-site scripting. It absorbs the 2021 split categories and also covers XML external entity style parser injection.",
    cwes: [
      "CWE-79",
      "CWE-89",
      "CWE-73",
      "CWE-74",
      "CWE-77",
      "CWE-78",
      "CWE-94",
      "CWE-611",
      "CWE-643",
      "CWE-917",
      "CWE-943",
      "CWE-1336",
    ],
    wstgFocus: [
      "WSTG-INPV-05",
      "WSTG-INPV-01",
      "WSTG-INPV-02",
      "WSTG-INPV-12",
      "WSTG-INPV-11",
      "WSTG-INPV-18",
      "WSTG-INPV-07",
      "WSTG-CLNT-01",
    ],
    detection: [
      "Quote or metacharacter payloads that change query results, error text, record counts or response length.",
      "Command output, delays or collaborator callbacks from parameters passed to system tools.",
      "Template or expression payloads such as 7*7 evaluating inside a rendered response.",
      "Unencoded input reflected into HTML, attributes, script blocks or DOM sinks.",
      "Parser errors, external entity resolution or unexpected outbound requests triggered by XML input.",
    ],
    remediation: [
      "Use parameterised queries, prepared statements and safe ORM APIs for all database access; never concatenate input into queries or filters.",
      "Pass data to interpreters as arguments instead of shell strings, and never eval, exec or include user-controlled input.",
      "Apply context-aware output encoding for HTML, attribute, URL, JavaScript and CSS contexts, backed by a strict Content-Security-Policy.",
      "Disable external entity and DTD processing in every XML parser and reject unexpected content types.",
      "Validate input against an allow-list of the expected shape and sanitise rich text with a maintained library.",
    ],
  },  {
    id: "A06:2025",
    rank: 6,
    title: "Insecure Design",
    summary:
      "Weaknesses that come from the design rather than a coding slip: missing threat modelling, no control for a specific business flow, unrestricted resource consumption and missing abuse controls. In 2025, workflow bypasses, forged requests and upload type control are typically reported here.",
    cwes: [
      "CWE-209",
      "CWE-269",
      "CWE-434",
      "CWE-501",
      "CWE-522",
      "CWE-602",
      "CWE-799",
      "CWE-840",
      "CWE-841",
      "CWE-1021",
    ],
    wstgFocus: [
      "WSTG-BUSL-01",
      "WSTG-BUSL-02",
      "WSTG-BUSL-04",
      "WSTG-BUSL-06",
      "WSTG-BUSL-07",
      "WSTG-BUSL-08",
      "WSTG-BUSL-09",
    ],
    detection: [
      "Multi-step flows that complete when a mandatory step is skipped, repeated or reordered.",
      "Impossible business values such as negative amounts, mismatched totals or reversed date ranges accepted and persisted.",
      "Race windows where parallel requests duplicate a one-time effect such as a redemption or vote.",
      "Uploads whose type or content is accepted without validation, scanning or safe storage.",
      "No rate limiting, alerting or added friction on obviously abusable functions.",
    ],
    remediation: [
      "Threat-model each feature and flow before implementation and record the abuse cases it must resist.",
      "Enforce business rules and state transitions server-side at every step, never trusting client sequence or hidden fields.",
      "Make critical operations idempotent and transactional so concurrent requests cannot double-apply an effect.",
      "Allow-list file types, inspect content, store uploads outside the web root and serve them through a hardened path.",
      "Design abuse controls up front: quotas, step-up verification and audit trails tied to the business action.",
    ],
  },
  {
    id: "A07:2025",
    rank: 7,
    title: "Authentication Failures",
    summary:
      "Anything that lets an attacker become or remain an authenticated user: credential stuffing and brute force, weak password policy, missing MFA, broken reset and remember-me flows, session fixation and sessions that never expire or invalidate. Session management findings are usually reported in this category in 2025.",
    cwes: [
      "CWE-255",
      "CWE-287",
      "CWE-288",
      "CWE-290",
      "CWE-307",
      "CWE-384",
      "CWE-521",
      "CWE-620",
      "CWE-640",
      "CWE-798",
    ],
    wstgFocus: [
      "WSTG-ATHN-02",
      "WSTG-ATHN-03",
      "WSTG-ATHN-04",
      "WSTG-ATHN-07",
      "WSTG-ATHN-09",
      "WSTG-IDNT-04",
      "WSTG-SESS-03",
      "WSTG-SESS-06",
    ],
    detection: [
      "Login, reset or registration responses that differ for existing and non-existing accounts.",
      "Repeated failed logins with no lockout, delay, CAPTCHA or alert.",
      "Session identifiers that stay the same across authentication, or that still work after logout.",
      "Passwords accepted that are short, common, context-specific or known-breached.",
      "Reset or remember-me tokens that are guessable, long-lived, reusable or valid for another account.",
    ],
    remediation: [
      "Deploy MFA, phishing-resistant where possible, and build on maintained identity frameworks rather than custom authentication code.",
      "Rate-limit and lock out credential attempts per account and per source, and alert on anomalies.",
      "Adopt a length-first password policy checked against breached-password lists, and support password managers.",
      "Rotate session identifiers on authentication and privilege change, and invalidate sessions server-side on logout, reset and password change.",
      "Generate reset and remember-me tokens with high entropy, bind them to the account, and expire them after one use.",
    ],
  },  {
    id: "A08:2025",
    rank: 8,
    title: "Software or Data Integrity Failures",
    summary:
      "Reliance on software, data or infrastructure whose integrity is never verified: unsigned or tampered artefacts, insecure deserialisation, unsigned updates, poisoned pipelines and untrusted data crossing a trust boundary. Where A03 covers the components themselves, A08 covers whether their integrity was actually checked.",
    cwes: [
      "CWE-345",
      "CWE-353",
      "CWE-426",
      "CWE-494",
      "CWE-502",
      "CWE-565",
      "CWE-829",
      "CWE-830",
      "CWE-915",
    ],
    wstgFocus: [
      "WSTG-BUSL-03",
      "WSTG-BUSL-09",
      "WSTG-INPV-14",
      "WSTG-CLNT-13",
      "WSTG-CONF-10",
    ],
    detection: [
      "Client-supplied data whose checksum, HMAC or signature is accepted after tampering, removal or replay.",
      "Serialised payloads (Java, .NET ViewState, PHP, pickle, YAML) deserialised from client input.",
      "Third-party scripts, JSONP or cross-origin script responses trusted with user data.",
      "Dangling DNS or storage resources a third party can claim and serve content from.",
      "Stored input that only becomes dangerous when a later automated process consumes it.",
    ],
    remediation: [
      "Verify integrity of every artefact and payload before use with signatures, HMACs or checksums and keys that never leave the server.",
      "Avoid native deserialisation of untrusted data; prefer strict schemas such as JSON with explicit type allow-lists.",
      "Pin third-party assets and require Subresource Integrity so a compromised CDN cannot alter them.",
      "Treat build, deployment and update channels as trusted infrastructure with signed artefacts and least-privilege credentials.",
      "Re-validate stored data when it is consumed instead of assuming it was safe when it was written.",
    ],
  },
  {
    id: "A09:2025",
    rank: 9,
    title: "Security Logging and Alerting Failures",
    summary:
      "Security events that are not logged, not monitored or not acted on, so attacks stay undetected and investigations lack evidence; the 2025 wording stresses alerting, not logging alone. Missing lockout, unmonitored abuse and unnoticed error conditions are reported here.",
    cwes: [
      "CWE-117",
      "CWE-223",
      "CWE-390",
      "CWE-392",
      "CWE-532",
      "CWE-778",
      "CWE-779",
    ],
    wstgFocus: [
      "WSTG-BUSL-07",
      "WSTG-ATHN-03",
      "WSTG-BUSL-05",
      "WSTG-CONF-02",
      "WSTG-ERRH-01",
      "WSTG-SESS-09",
    ],
    detection: [
      "Hundreds of failed logins, enumerations or forged requests with no throttle, lockout or alert.",
      "Errors that return evidence to the client while leaving nothing in the logs.",
      "Abusable functions used without limits and without a monitoring or alerting signal.",
      "Logs that omit authentication, authorisation and administrative actions, or are stored where an attacker can alter them.",
      "Session hijacking and concurrent-session anomalies that nobody detects.",
    ],
    remediation: [
      "Log authentication, authorisation, administrative and input-validation failures with enough context to reconstruct the event.",
      "Centralise logs in a write-once store and alert on thresholds and patterns instead of relying on manual log review.",
      "Never write credentials, tokens or unnecessary personal data to logs; redact before persistence.",
      "Make every alert actionable with an owner, severity and documented response runbook.",
      "Add in-application detection such as lockout counters, anomaly alerts and monitoring of abuse-prone endpoints.",
    ],
  },
  {
    id: "A10:2025",
    rank: 10,
    title: "Mishandling of Exceptional Conditions",
    summary:
      "New in 2025, taking the place SSRF held in 2021: code that fails open, ignores errors, or mishandles missing input, exceptions and NULL values, so security controls are skipped or internal detail is exposed. Verbose stack traces and inconsistent error behaviour, including padding-oracle style oracles, are reported here.",
    cwes: [
      "CWE-209",
      "CWE-234",
      "CWE-248",
      "CWE-390",
      "CWE-391",
      "CWE-476",
      "CWE-636",
      "CWE-754",
    ],
    wstgFocus: [
      "WSTG-ERRH-01",
      "WSTG-ERRH-02",
      "WSTG-CRYP-02",
      "WSTG-INPV-13",
      "WSTG-BUSL-04",
    ],
    detection: [
      "Stack traces, framework versions, file paths or SQL fragments returned to the client.",
      "Different error text, status codes or timing that distinguish padding, token or user validity.",
      "Authorisation or validation skipped when a parameter is missing, malformed or NULL.",
      "Fail-open behaviour where the request succeeds because the control could not be evaluated.",
      "Unhandled exceptions that crash a worker, corrupt state or force a restart.",
    ],
    remediation: [
      "Catch, log and translate errors into one generic client response shape carrying a correlation id for support.",
      "Fail closed: any error on an authorisation or validation path must deny the request.",
      "Handle optional and nullable inputs explicitly, treating absent, empty and null as distinct defined cases.",
      "Return constant-time, uniform responses on cryptographic and token validation paths.",
      "Exercise exception paths in CI with fault injection and fuzzing so error branches are tested before production.",
    ],
  },
];